import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import {
  createEdgeHandler, jsonResponse, requireAuth,
  validateString, validateNumber, validateInt,
  mockTxId, mockBlockHeight,
  type RequestContext,
} from "../_shared/utils.ts";

// ========== Content Generation Engine ==========

interface GeneratedContent {
  content: string;
  type: string;
  metadata: { wordCount: number; estimatedReadTime: string };
}

function generateContent(prompt: string): GeneratedContent {
  const lower = prompt.toLowerCase();
  let type = 'general';
  let content = '';

  if (lower.includes('blog') || lower.includes('article')) {
    type = 'blog_post';
    content = `# ${prompt}\n\nIn the rapidly evolving landscape of Web3 technology, autonomous agents are reshaping how we think about digital services. Molbot Studio enables creators to assemble, execute, and earn with intelligent bots on the Stacks blockchain.\n\n## Key Insights\n\n1. **Decentralized Commerce**: Bots transact using sBTC and USDCx via the x402 protocol.\n2. **Bitcoin Security**: Every transaction is anchored to Bitcoin through Proof of Transfer.\n3. **Scalable Architecture**: The modular design allows infinite extensibility.\n\n## Conclusion\n\nThe future of autonomous agent economies is being built on Stacks.\n\n---\n*Generated by Molbot Studio Content Bot • Powered by x402*`;
  } else if (lower.includes('tweet') || lower.includes('social')) {
    type = 'social_post';
    content = `🤖 Just discovered @AgentStudio — a no-code platform for building autonomous bots on #Stacks!\n\n💰 Bots pay each other using sBTC via x402\n📊 USDCx streaming for time-based services\n🔒 All secured by Bitcoin via Proof of Transfer\n\nThe future of AI-powered commerce is here. #Bitcoin #Web3 #AI`;
  } else if (lower.includes('email') || lower.includes('newsletter')) {
    type = 'email';
    content = `Subject: Introducing Agent Studio — Build Autonomous Bots on Bitcoin\n\nHi there,\n\nWe're excited to announce Agent Studio, the first no-code platform for creating autonomous molbots on the Stacks blockchain.\n\nWhat makes it special:\n• Create bots without writing code\n• Monetize with sBTC micropayments (x402 protocol)\n• Stream payments with USDCx\n• Bitcoin-anchored security via Proof of Transfer\n\nGet started today at agentstudio.io\n\nBest,\nThe Agent Studio Team`;
  } else if (lower.includes('summary') || lower.includes('summarize')) {
    type = 'summary';
    content = `**Summary**: ${prompt}\n\nKey points:\n• Agent Studio provides a no-code interface for bot creation on Stacks\n• Payments flow through x402 protocol using sBTC and USDCx\n• All operations are anchored to Bitcoin via Proof of Transfer\n• The platform supports both fixed-price and streaming payment models`;
  } else {
    content = `**Generated Content for: "${prompt}"**\n\nAgent Studio's autonomous bots leverage the Stacks blockchain to provide decentralized, Bitcoin-secured services. Using the x402 payment protocol, bots can autonomously transact with each other using sBTC for fixed payments or USDCx for streaming services.\n\n---\n*Powered by Agent Studio • x402 Protocol • USDCx*`;
  }

  const words = content.split(/\s+/).length;
  return {
    content, type,
    metadata: { wordCount: words, estimatedReadTime: `${Math.max(1, Math.ceil(words / 200))} min` },
  };
}

// ========== Route Handlers ==========

async function handleGenerate(ctx: RequestContext) {
  requireAuth(ctx.userId);

  const prompt = validateString(ctx.body.prompt as string, 'prompt', 1, 1000);
  const botId = typeof ctx.body.botId === 'number' ? ctx.body.botId : null;
  const requestId = ctx.requestId;

  let priceAmount = 0.50;
  let providerBotId = botId;

  if (botId) {
    const { data: bot } = await ctx.supabase.from('bots').select('*').eq('id', botId).eq('active', true).single();
    if (bot) {
      priceAmount = bot.price_amount;
      providerBotId = bot.id;
    } else {
      providerBotId = null;
    }
  }

  const paymentTxId = mockTxId();
  const blockHeight = mockBlockHeight();

  await ctx.supabase.from('transactions').insert({
    tx_id: paymentTxId, to_bot_id: providerBotId, amount: priceAmount,
    asset: 'USDCx', tx_type: 'payment', status: 'confirmed',
    metadata: {
      protocol: 'x402', service: 'content-generation', requestId,
      clarityContract: 'skill-bot.process-request', blockHeight,
      skillBotEvent: { topic: 'skill-request', botId: providerBotId, requester: ctx.userId, asset: 'USDCx' },
    },
  });

  const result = generateContent(prompt);

  // Record job if bot was specified
  if (providerBotId) {
    const { data: userBots } = await ctx.supabase.from('bots').select('id').eq('owner_id', ctx.userId).limit(1);
    if (userBots?.length) {
      await ctx.supabase.from('jobs').insert({
        requester_bot_id: userBots[0].id, provider_bot_id: providerBotId,
        requester_user_id: ctx.userId, status: 'completed', payment_tx_id: paymentTxId,
        result: { type: result.type, content: result.content, promptLength: prompt.length },
      });
    }
  }

  return jsonResponse({
    requestId, content: result.content, contentType: result.type,
    metadata: result.metadata,
    payment: {
      txId: paymentTxId, amount: priceAmount, asset: 'USDCx', protocol: 'x402', blockHeight,
      clarityEvent: { topic: 'skill-request', botId: providerBotId, price: priceAmount, asset: 'USDCx' },
    },
  });
}

async function handleListSkillBots(ctx: RequestContext) {
  const skill = ctx.url.searchParams.get('skill');
  let query = ctx.supabase.from('bots').select('*').eq('active', true);
  if (skill) query = query.contains('skills', [skill]);
  const { data } = await query.order('created_at', { ascending: false }).limit(50);
  return jsonResponse(data || []);
}

// ========== Route Map ==========

const routes = {
  'generate': { method: 'POST' as const, handler: handleGenerate, rateLimit: 10 },
  'list-skill-bots': { method: 'GET' as const, handler: handleListSkillBots, public: true },
};

serve(createEdgeHandler('skill-bot-api', routes));
