import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version, idempotency-key',
};

// ========== Helpers ==========

function jsonResponse(data: unknown, status = 200): Response {
  return new Response(JSON.stringify(data), { status, headers: { ...corsHeaders, 'Content-Type': 'application/json' } });
}

function log(level: string, message: string, data?: Record<string, unknown>) {
  const entry = { timestamp: new Date().toISOString(), level, service: 'skill-bot-api', message, ...data };
  if (level === 'error') console.error(JSON.stringify(entry));
  else console.log(JSON.stringify(entry));
}

function mockTxId(): string {
  return `0x${Array.from({ length: 64 }, () => Math.floor(Math.random() * 16).toString(16)).join('')}`;
}

async function authenticateUser(req: Request, supabaseUrl: string, supabaseAnonKey: string): Promise<string | null> {
  const authHeader = req.headers.get('Authorization');
  if (!authHeader?.startsWith('Bearer ')) return null;
  const token = authHeader.replace('Bearer ', '');
  const client = createClient(supabaseUrl, supabaseAnonKey, {
    global: { headers: { Authorization: authHeader } },
  });
  const { data, error } = await client.auth.getClaims(token);
  if (error || !data?.claims) return null;
  return data.claims.sub as string;
}

// ========== Rate Limiting ==========

const rateLimitMap = new Map<string, { count: number; resetAt: number }>();

function checkRateLimit(key: string, max = 10): boolean {
  const now = Date.now();
  const entry = rateLimitMap.get(key);
  if (!entry || now > entry.resetAt) {
    rateLimitMap.set(key, { count: 1, resetAt: now + 60_000 });
    return true;
  }
  if (entry.count >= max) return false;
  entry.count++;
  return true;
}

// ========== Content Generation ==========

function generateContent(prompt: string): { content: string; type: string } {
  const lower = prompt.toLowerCase();

  if (lower.includes('blog') || lower.includes('article')) {
    return {
      type: 'blog_post',
      content: `# ${prompt}\n\nIn the rapidly evolving landscape of Web3 technology, autonomous agents are reshaping how we think about digital services. Agent Studio enables creators to build, deploy, and monetize intelligent bots on the Stacks blockchain.\n\n## Key Insights\n\n1. **Decentralized Commerce**: Bots transact using sBTC and USDCx via the x402 protocol.\n2. **Bitcoin Security**: Every transaction is anchored to Bitcoin through Proof of Transfer.\n3. **Scalable Architecture**: The modular design allows infinite extensibility.\n\n## Conclusion\n\nThe future of autonomous agent economies is being built on Stacks.\n\n---\n*Generated by Agent Studio Content Bot • Powered by x402*`,
    };
  }

  if (lower.includes('tweet') || lower.includes('social')) {
    return {
      type: 'social_post',
      content: `🤖 Just discovered @AgentStudio — a no-code platform for building autonomous bots on #Stacks!\n\n💰 Bots pay each other using sBTC via x402\n📊 USDCx streaming for time-based services\n🔒 All secured by Bitcoin via Proof of Transfer\n\nThe future of AI-powered commerce is here. #Bitcoin #Web3 #AI`,
    };
  }

  if (lower.includes('email') || lower.includes('newsletter')) {
    return {
      type: 'email',
      content: `Subject: Introducing Agent Studio — Build Autonomous Bots on Bitcoin\n\nHi there,\n\nWe're excited to announce Agent Studio, the first no-code platform for creating autonomous molbots on the Stacks blockchain.\n\nWhat makes it special:\n• Create bots without writing code\n• Monetize with sBTC micropayments (x402 protocol)\n• Stream payments with USDCx\n• Bitcoin-anchored security via Proof of Transfer\n\nGet started today at agentstudio.io\n\nBest,\nThe Agent Studio Team`,
    };
  }

  if (lower.includes('summary') || lower.includes('summarize')) {
    return {
      type: 'summary',
      content: `**Summary**: ${prompt}\n\nKey points:\n• Agent Studio provides a no-code interface for bot creation on Stacks\n• Payments flow through x402 protocol using sBTC and USDCx\n• All operations are anchored to Bitcoin via Proof of Transfer\n• The platform supports both fixed-price and streaming payment models`,
    };
  }

  return {
    type: 'general',
    content: `**Generated Content for: "${prompt}"**\n\nAgent Studio's autonomous bots leverage the Stacks blockchain to provide decentralized, Bitcoin-secured services. Using the x402 payment protocol, bots can autonomously transact with each other using sBTC for fixed payments or USDCx for streaming services.\n\n---\n*Powered by Agent Studio • x402 Protocol • USDCx*`,
  };
}

// ========== Main ==========

serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response(null, { headers: corsHeaders });

  const startTime = Date.now();

  try {
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseAnonKey = Deno.env.get('SUPABASE_ANON_KEY')!;
    const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;

    const url = new URL(req.url);
    const action = url.searchParams.get('action');
    if (!action) return jsonResponse({ error: 'Missing action parameter' }, 400);

    let body: Record<string, unknown> = {};
    if (req.method === 'POST') {
      try { body = await req.json(); } catch { return jsonResponse({ error: 'Invalid JSON body' }, 400); }
    }

    const userId = await authenticateUser(req, supabaseUrl, supabaseAnonKey);
    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    // ========== GENERATE CONTENT ==========
    if (action === 'generate' && req.method === 'POST') {
      if (!userId) return jsonResponse({ error: 'Unauthorized' }, 401);
      if (!checkRateLimit(userId, 10)) return jsonResponse({ error: 'Too many requests. Max 10 generations per minute.' }, 429);

      const prompt = body.prompt;
      if (typeof prompt !== 'string' || prompt.trim().length === 0) {
        return jsonResponse({ error: 'Prompt is required and must be a non-empty string' }, 400);
      }
      if (prompt.length > 1000) return jsonResponse({ error: 'Prompt must be under 1000 characters' }, 400);

      const trimmedPrompt = prompt.trim();
      const botId = typeof body.botId === 'number' ? body.botId : null;
      const requestId = crypto.randomUUID();

      let priceAmount = 0.50;
      let providerBotId = botId;

      if (botId) {
        const { data: bot } = await supabase.from('bots').select('*').eq('id', botId).eq('active', true).single();
        if (bot) { priceAmount = bot.price_amount; providerBotId = bot.id; }
        else { providerBotId = null; }
      }

      const paymentTxId = mockTxId();

      await supabase.from('transactions').insert({
        tx_id: paymentTxId, to_bot_id: providerBotId, amount: priceAmount,
        asset: 'USDCx', tx_type: 'payment', status: 'confirmed',
        metadata: {
          protocol: 'x402', service: 'content-generation', requestId,
          clarityContract: 'skill-bot.process-request',
          blockHeight: 100000 + Math.floor(Math.random() * 10000),
          skillBotEvent: { topic: 'skill-request', botId: providerBotId, requester: userId, asset: 'USDCx' },
        },
      });

      const result = generateContent(trimmedPrompt);

      if (providerBotId) {
        const { data: userBots } = await supabase.from('bots').select('id').eq('owner_id', userId).limit(1);
        if (userBots?.length) {
          await supabase.from('jobs').insert({
            requester_bot_id: userBots[0].id, provider_bot_id: providerBotId,
            requester_user_id: userId, status: 'completed', payment_tx_id: paymentTxId,
            result: { type: result.type, content: result.content, promptLength: trimmedPrompt.length },
          });
        }
      }

      log('info', 'Content generated', { requestId, userId, contentType: result.type, priceAmount, duration: Date.now() - startTime });

      return jsonResponse({
        requestId, content: result.content, contentType: result.type,
        payment: {
          txId: paymentTxId, amount: priceAmount, asset: 'USDCx', protocol: 'x402',
          clarityEvent: { topic: 'skill-request', botId: providerBotId, price: priceAmount, asset: 'USDCx' },
        },
      });
    }

    // ========== LIST SKILL BOTS ==========
    if (action === 'list-skill-bots' && req.method === 'GET') {
      const { data } = await supabase.from('bots').select('*').eq('active', true).order('created_at', { ascending: false }).limit(50);
      return jsonResponse(data || []);
    }

    return jsonResponse({ error: 'Unknown action', availableActions: ['generate', 'list-skill-bots'] }, 400);

  } catch (error) {
    const message = error instanceof Error ? error.message : 'Unknown error';
    log('error', 'Skill bot error', { error: message, duration: Date.now() - startTime });
    return jsonResponse({ error: 'Internal server error' }, 500);
  }
});
