// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? (import.meta as any).env.VITE_SUPABASE_ANON_KEY;

const createQueryStub = () => {
  const configError = new Error('Lovable Cloud is not configured for this preview.');
  const result = { data: null, error: configError, count: null, status: 503, statusText: 'Service Unavailable' };

  const proxy: any = new Proxy(
    {},
    {
      get(_, prop) {
        if (prop === 'then') {
          return (resolve: (value: typeof result) => void) => resolve(result);
        }
        return () => proxy;
      },
    }
  );

  return proxy;
};

const createFallbackClient = () => {
  const configError = new Error('Lovable Cloud is not configured for this preview.');

  return {
    auth: {
      onAuthStateChange: () => ({
        data: {
          subscription: {
            unsubscribe: () => undefined,
          },
        },
      }),
      getSession: async () => ({ data: { session: null }, error: configError }),
      signUp: async () => ({ data: { user: null, session: null }, error: configError }),
      signInWithPassword: async () => ({ data: { user: null, session: null }, error: configError }),
      signOut: async () => ({ error: null }),
    },
    from: () => createQueryStub(),
    rpc: () => createQueryStub(),
    functions: {
      invoke: async () => ({ data: null, error: configError }),
    },
  } as unknown as SupabaseClient<Database>;
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    })
  : createFallbackClient();